### ISSUE TITLE
[BUG] footer.mustache에서 index.js 로드 못함

### ISSUE THREAD

**Issue by kimhanui** [kimhanui/2020-InterfaceApp-api#2]
### Expectation & Result
- 게시글 등록 버튼 누르면 alert 떠야함

### Error Log
- chrome에서 개발자도구 로그
![image](https://user-images.githubusercontent.com/30483337/89922867-9f79e080-dc3a-11ea-9f52-0f3230abe9b5.png)
- intellij 상 로그 무

### Related page & issue
- 144pg

**Comment by kimhanui** [comment]
### Resolved 
- static 경로 관련 오탈자 확인
![image](https://user-images.githubusercontent.com/30483337/89925139-f6cd8000-dc3d-11ea-8461-2eff406124a9.png)
경로를 실제로 copy & paste해보니   
위의 `js.app`은 -> `/static/js/app`  
아래의 `js.app`(내가 썼던 것ㅠㅠ)은 -> `/static/js.app`

수정 후 정상 작동 확인

**Comment by oldaim** [comment]
김하늬!김하늬!김하늬!김하늬!김하늬!김하늬!김하늬!
