### ISSUE TITLE
[BUG]: follow 처리 오류

### ISSUE THREAD

**Issue by 2kyung19** [kimhanui/2020-InterfaceApp-api#22]
친애하는 주인장에게,
나는 문제를 겪고있다.
당신은 나의 추종자가 되었다.
나는 당신을 모른다.
해결해주세요.
from james

**Comment by kimhanui** [comment]
To James  
I am From Korea. Nice to meet you.    
I was impressed by your projects. And your grass is 듬성 like me.  
So I followed you.  
Thank you.  
김하늬 올림.

**Comment by 2kyung19** [comment]
친애하는 주인장에게,
Ok. I do ㅇㅈ 
If you want to see 빽빽 gress
go here @riyenas0925
his grass is very 빽빽
but hair is 듬성
Thanks!
from james

**Comment by kimhanui** [comment]
To james
wow..... his grass is like a jungle.  
But it's ok.   
My hair is MORE 빽뺵.  
It is 공평.       
Thanks!   
김하늬 올림
